(require 'editorconfig-core)

(ert-deftest editorconfig-core--merge-two-properties ()
  (should (equal (editorconfig-core--merge-two-properties '(("a" . "1") ("b" . "1"))
                                                          nil)
                 '(("a" . "1") ("b" . "1"))))
  (should (equal (editorconfig-core--merge-two-properties nil
                                                          '(("a" . "1") ("b" . "1")))
                 '(("a" . "1") ("b" . "1"))))
  (should (equal (editorconfig-core--merge-two-properties '(("a" . "1") ("b" . "1"))
                                                          '(("a" . "2") ("c" . "2")))
                 '(("a" . "2") ("b" . "1") ("c" . "2"))))
  (should (equal (editorconfig-core--merge-two-properties '(("a" . "1") ("b" . "1") ("c" . "1"))
                                                          '(("a" . "2") ("c" . "2")))
                 '(("a" . "2") ("b" . "1") ("c" . "2"))))
  (should (equal (editorconfig-core--merge-two-properties '(("a" . "1") ("b" . "1") ("c" . "1"))
                                                          '(("b" . "2") ("d" . "2")))
                 '(("a" . "1") ("b" . "2") ("c" . "1") ("d" . "2"))))
  )
